[project]
name = "ComfyUI_srt2speech"
description = "This repo need to use with any TTS, it will be automate subtitle.srt for TTS, check it out from my video tutorial here https://youtu.be/pXEbXhNceUo?si=yC2h3SE-cWqKN2bz""
version = "1.0.0"
license = {file = "LICENSE"}

dependencies = ["setproctitle>=1.2.0", "attrdict>=2.0.1", "librosa>=0.9.2", "pydub>=0.25.1", "pyloudnorm>=0.1.0", "x-transformers>=0.25.0", "torchdiffeq>=0.2.2", "openai-whisper>=20230314", "tqdm>=4.65.0", "torch>=2.0.0", "numpy>=1.20.0", "requests>=2.28.0", "pyyaml>=6.0"]

[project.urls]
Repository = "https://github.com/1038lab/ComfyUI-MegaTTS"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "ailab"
DisplayName = "ComfyUI-MegaTTS"
Icon = ""